name = "mytask-cf"
main = "src/index.ts"
compatibility_date = "2026-05-26"
workers_dev = true

routes = [
  { pattern = "cf.cchk.uk", custom_domain = true }
]

[assets]
directory = "../static"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "mytask_cf"
database_id = "4aa0013f-dba6-46fd-82bd-29e9221a01c2"
migrations_dir = "migrations"


[vars]
OPENAI_MODEL = "meta/llama-3.1-8b-instruct"
